server:
  port: 8090

spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-huespedes
              uri: lb://ms-huespedes
              predicates:
                - Path=/api/huespedes/**
              filters:
                - StripPrefix=2
                
            - id: ms-habitaciones
              uri: lb://ms-habitaciones
              predicates:
                - Path=/api/habitaciones/**
              filters:
                - StripPrefix=2

            - id: ms-reservas
              uri: lb://ms-reservas
              predicates:
               - Path=/api/reservas/**
              filters:
               - StripPrefix=2
    loadbalancer:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka